version: '3.0'
services:
  postgres:
    env_file:
      - .env
    container_name: postgres
    build: ./postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command:
      - postgres
      - -c
      - PORT=${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: on-failure
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
volumes:
  postgres_data:
